s1 = R(None, 'hoffen')
Präsens(s1)
s2 = R(s1, '1s', 'Hoffende')
Vorfeld(s2)
s3 = R(s1, 'sein', 'auf')
Infinit(s3)
s4 = R(s3, 'Vater', 'Prädikativ')
Generisch(s4)
s5 = R(s3, 'bald')
Satzende(s1)

showresult(s1)
